config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about'

  resources :users, only: [:index, :create, :show, :edit, :update]
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user
  
  def get_profile_image(width, height)
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  #投稿一覧ページ
  def index
  end
  
  def create
  end
  
  #投稿詳細ページ
  def show
  end
  
  #投稿編集ページ
  def edit
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #ユーザー一覧ページ
  def index
    @user = User.all
  end

  #ログイン後ページ（ログインユーザー詳細ページ）
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to user_path(resource)
  end

  #プロフィール変更ページ
  def edit
    #is_matching_login_user
    @user = User.find(user_params)
  end
  
  #プロフィール変更を更新する
  def update
    #is_matching_login_user
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<%= render 'users/list', user: @user, book: @book %>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/about.html.erb
<div class="container">
  <h1>
    Welcome to
    <strong>Bookers</strong>
    !!
  </h1>
</div>

app/views/homes/top.html.erb
<div class="container">
  <h1>
    Welcome to
    <strong>Bookers</strong>
    !
  </h1>
  <p>
    In
    <strong>Bookers</strong>
    ,
  </p>
  <p>you can share and exchange your opinions, and emotions</p>
  <p>about various books!</p>
</div>
<div class="btn-wrapper">
  <p class="btn">
    <%= link_to "Log in", user_session_path %>
  </p>
  <p class="btn">
    <%= link_to "Sign up", new_user_registration_path %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header>
      <% if user_signed_in? %>
        <li>
          <%= link_to "Home", user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <li>
          <%= link_to "Books", books_path %>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Sign up", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "Log in", new_user_session_path %>
        </li>
      <% end %>
    </header>
    
    <%= yield %>
    
    <footer>
      <div class="container">
        <div class="footer">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<div class="content">
  
  <h2>User Info</h2>
  
  <div class="user-info">
    <p>name</p>
    <p><%= user.name %></p>
  </div>
  
  <div class="user-info">
    <p>introduction</p>
    <p><%= user.introduction %></p>
  </div>
  
  <% if user.id == current_user.id %>
    <p><%= link_to "編集", edit_user_path(user) %></p>
  <% end %>

  
  <h2>New book</h2>
  <div class="new-book">
    <%= form_with model:book do |f| %>
      <p>Title</p>
      <%= f.text_field :title %>
      
      <p>Opinion</p>
      <%= f.text_area :body %>
      
      <%= f.submit 'Create Book' %>
    <% end %>
  </div>
  
</div>

app/views/users/edit.html.erb
<div class="conteiner">
  <h2>User info</h2>
  <div class="content">
    <%= form_with model: @user do |f| %>
    <label for="inputName">Name</label>
    <%= f.text_field :name, autofocus: true %>
    
    <label for="inputImape">Image</label>
    <%= f.file_field :profile_image, accept: 'image/*' %>
    
    <label for="inputIntroduction">Introduction</label>
    <%= f.text_area :introduction %>
    
    <%= f.submit 'Update User' %>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<%= render 'list', user: @user, book: @book %>

<div class="book-table">
  <h2>Books</h2>
  <div class="book-head">
    <p></p>
    <p>Title</p>
    <p>Opinion</p>
    <p></p>
  </div>
  
  <div class="book-list">
    <%= @books.each do |book| %>
      <p>
        <%= image_tag @user.get_profile_image(100,100) %><br>
        <%= book.user.name %>
      </p>
      <p><%= book.title %></p>
      <p><%= book.body %></p>
    <% end %>
  </div>
</div>